#!/bin/bash
# Get the absolute path to the script
SCRIPT_PATH=$(realpath "$0" 2>/dev/null || readlink -f "$0")

# Extract the directory of the script
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

$SCRIPT_DIR/../debian/key_install
